# Generated by Django 4.2.13 on 2024-07-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employeeNo',
            new_name='employeeId',
        ),
    ]
